apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8-e2-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8-e2e-app 
  template:
    metadata:
      labels:
        app: jenkins-k8-e2e-app 
    spec:
      containers:
        - name: jenkins-k8-e2e-app 
          image: abooumair/jenkins-k8-e2e:latest 
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
